== 流程说明（重要）：

1. 客户端（浏览器）发送请求，直接请求到 DispatcherServlet；
1. DispatcherServlet 根据请求信息调用 HandlerMapping，解析请求对应的 Handler；
1. 解析到对应的 Handler（也就是我们平常说的 Controller 控制器）后，开始由 HandlerAdapter 适配器处理；
1. HandlerAdapter 会根据 Handler 来调用真正的处理器开处理请求，并处理相应的业务逻辑；
1. 处理器处理完业务后，会返回一个 ModelAndView 对象，Model 是返回的数据对象，View 是个逻辑上的 View；
1. ViewResolver 会根据逻辑 View 查找实际的 View；
1. DispaterServlet 把返回的 Model 传给 View（视图渲染）；
1. 把 View 返回给请求者（浏览器）。

### 处理请求映射 - HandlerMapping

- SimpleUrlHandlerMapping类通过配置文件把URL映射到Controller类。
- DefaultAnnotationHandlerMapping类通过注解把URL映射到Controller类。

### 视图处理接口 - ViewResolver

- UrlBasedViewResolver类 通过配置文件，把一个视图名交给到一个View来处理。

### 异常处理接口 - HandlerExceptionResolver

- `@ExceptionHandler` 注解

- `@ControllerAdvice` 注解

- `HandlerExceptionResolver`接口


=== 设置Content Type

[source,text]
.request_mapping.txt
----
@GetMapping(value = "qrcode", produces = "image/jpeg")
----

=== 切面

[source,java]
.SomeAspect.java
----
import org.aspectj.lang.JoinPoint;
import org.aspectj.lang.annotation.Aspect;
import org.aspectj.lang.annotation.Before;
import org.aspectj.lang.annotation.Pointcut;

import org.springframework.context.annotation.Configuration;
import org.springframework.web.bind.annotation.ControllerAdvice;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.context.annotation.EnableAspectJAutoProxy;


@Aspect
@Configuration
@ControllerAdvice
@EnableAspectJAutoProxy
public class WebConfig {

    @Pointcut("@annotation(com.test.AnnoAspect)")
    public void annoAspect() {
    }

    @Before("annoAspect()")
    public void dealAnnoAspect(JoinPoint point) {
        // TODO
    }

    @ExceptionHandler(Exception.class)
    @ResponseBody
    public Object exceptionHandler(Exception e) {
        return Result.failure("系统错误 - " + e.getMessage());
    }
}
----

=== 获取HTTP请求

[source,java]
.GetRequest.java
----
import org.springframework.web.context.request.RequestContextHolder;
import org.springframework.web.context.request.ServletRequestAttributes;

import javax.servlet.http.HttpServletRequest;

public class GetRequest {

    public HttpServletRequest getRequest(){
        return ((ServletRequestAttributes) RequestContextHolder.getRequestAttributes()).getRequest();
    }

}
----